### ISSUE TITLE
.NET Framework exception on launch

### ISSUE THREAD

**Issue by Yadasko** [SilentSys/SLAM#1]
Hi there ! 

Just wanted to let you know about an exception that prevent me to use the soft.

On launch, that exceptions occurs. 
![capture](https://cloud.githubusercontent.com/assets/1543492/10122106/61fc256a-650c-11e5-8167-35003c62c7ec.PNG)

If I click on continue, the soft become this : 
![capture](https://cloud.githubusercontent.com/assets/1543492/10122109/9882fc44-650c-11e5-9050-18456c6217c8.PNG)

I'm running .NET Framework 4 on a Windows 7 x64 computer.
Cheers.

**Comment by SilentSys** [comment]
I just created an update. Try using v1.1.1 and let me know if that works for you.

Thanks!

**Comment by SilentSys** [comment]
Actually, forget about my previous comment. You must update to .net 4.5
https://www.microsoft.com/en-ca/download/details.aspx?id=30653

**Comment by Yadasko** [comment]
Oh man, I thought I had 4.5, but nah, it was 4. Works great now, thanks !
