### ISSUE TITLE
Allow AAC files

### ISSUE THREAD

**Issue by Ivoz** [SilentSys/SLAM#11]
Usually with .aac / .mp4 / .m4a extension

Most itunes music is in this format, a lot of youtube is as well

Others youtube uses are [Vorbis](http://www.vorbis.com/) & [Opus](http://www.opus-codec.org/), incase you care

**Comment by DidUknowiPwn** [comment]
Just convert them using Audacity or your own version tool.

**Comment by SilentSys** [comment]
Update 1.2.2 addresses this issue.

Thanks.

**Comment by Ivoz** [comment]
Nice! Thanks mate :+1:
