### ISSUE TITLE
I have forked this project and and created my version

### ISSUE THREAD

**Issue by MaticBabnik** [SilentSys/SLAM#111]
Is there any way to add it here or something?
Edit: I am a n00b in github!

**Comment by Ammar-Dayoub** [comment]
Push the branch you worked on to your forked repository,
Go to your forked repository on github and create a pull request (choose the branch you worked on)
It'll get reviewed and merged if it's ok
Also reference the issue you fixed (if you fixed any) using #theissuenumber

**Comment by MaticBabnik** [comment]
ok thanks
