### ISSUE TITLE
Can I change the display language and publish it?

### ISSUE THREAD

**Issue by Shuazijun** [SilentSys/SLAM#114]
=========================For Machine Translation===========================
==============================Warning================================

Hello, I am a program for beginners from China, I love this software (it let me into a DJ: D). Because the mainland CSGO agent, which can not be used SLAM, I change a part of the source code and VB form that made him into Chinese interface, and let SLAM to support CSGO China (http://www.csgo.com.cn/) version, I identified the steam version and the CSGO Version (Chinese have retained your donation link), add your donation links (I hope you don't mind), can I release it in the China area? You can find me alone to obtain the modified source code (see what is not appropriate, and optimize the code) in your permission before I will not release any documents.

Quote:

你好,我是来自中国的一名程序初学者,我非常喜欢这个软件(它让我变成了一个DJ :D ).由于大陆地区的CSGO被代理,导致无法使用SLAM,我更改了一部分源代码和VB窗体显示,使他变成中文界面,并且让SLAM单独支持CSGO中国版

官网:http://www.csgo.com.cn/

我区分了steam版和CSGO中国版(都保留了您的捐款链接),添加了自己的捐款链接(希望您不要介意),请问我能在中国地区发布么?您可以单独找我来获取修改后的源代码(看看有什么不合适并且优化代码),在您允许前我不会发布任何文件.

**Comment by SilentSys** [comment]
Sorry for the late response.

Yes, you may release your version.

Thanks.
