### ISSUE TITLE
ingame console interface

### ISSUE THREAD

**Issue by burelzor** [SilentSys/SLAM#12]
after a semi-succesful installation of slam im unable to see everything what should be displayed inside the console although slam itself works fine when it comes to playing the audio files. i can type in the numbers of the files or tags in the console and change the file with it but it just doesnt gets displayed
any idea what could cause this?

**Comment by SilentSys** [comment]
What is it that you are not seeing? The track list?

**Comment by burelzor** [comment]
i could fix it, it was a setting in my autoexec which i created through a autoexec creator and this was overwriting something so nothing was displayed in the console, so if someone else. so if someone else has this issue aswell check your autoexec. and yes when i was typing "exec slam" no output

**Comment by SilentSys** [comment]
I'm glad you resolved your issue.
