### ISSUE TITLE
Can it tagger in game event then play?

### ISSUE THREAD

**Issue by ovo4096** [SilentSys/SLAM#126]
Such as player death play music, such as player win play music....

**Comment by TypicalHog** [comment]
I'm like 90% sure you can only to that manually. Usually, when I'm close to dying - I load Roblox death sound/Minecraft oof/GTA wasted or something like that and press the play button at the exact moment when I die. When I'm spectating my teammates I often play hit market sound/punch sound when they kill someone. When we lose I play "Mission failed, we'll get 'em next time". This is just the surface of what can be done using SLAM. I have over 1100+ sounds and music. It just takes a lot of practice to get good at it:

1. Thinking of the best sound to play
2. Loading the correct sound (remembering the tags)
3. Playing it at the right moment
4. Being quick AF

**Comment by ovo4096** [comment]
I know current is this mode, I hope add event tagger the play mode.

Is there any implement problem with this?
