### ISSUE TITLE
Possibly broken after 12/17/2015 CS:GO update

### ISSUE THREAD

**Issue by Kamairo** [SilentSys/SLAM#14]
Hey,

the pre-compiled binary from your website fails to load tracks via ingame console commands and hotkeys (CS:GO) since today. If I manually load the tracks in the main form I can play the tracks via hotkey ingame.

I cloned and recompiled/debugged this project and I have the exact same issue when compiling on release. If I however compile in debug the function ```PollRelayWorker_DoWork``` gets a "2" in the command variable and loads a track on startup. After that I have no issues at all. I can loads tracks via hotkey etc. This sounds a little weird, but I am not that deep into VB to tell you where this is coming from. Just wanted to let you know.

**Comment by Kamairo** [comment]
After further debugging I think something is wrong with the config files writing and loading. I see you added userconfig support in 1.2.1 and you are searching for a "slam_relay.cfg", which I deleted some time ago, because I wanted to reset everything. Also I added a second steam user with CS:GO a few days ago on my system. So, maybe this has nothing to do with the update, but with the userconfigs. Funny thing this, the slam_relay.cfg does not seem to be created again on my system, neither in userdata, nor in csgo/cfg.

**Comment by Kamairo** [comment]
The problem is, that I cannot reproduce the issue. Friends of mine btw also have the same problem.  The funny thing is, that some binaries work for me, but not for my friends others also do not work for me. I found out you are creating and deleting the slam_relay.cfg everytime you load a title, is that correct? If that's the case then maybe there's the issue and the cause of the randomness. I see that the relay config is written by CS GO and not by SLAM, but deleted by SLAM. I have the feeling this might cause synchronisation problems, i.e. CS GO isn't done writing the file, but SLAM is already trying to read it.

**Comment by Kamairo** [comment]
Friend of mine btw reported that he used a registry cleaner and SLAM started working again after that.

**Comment by Keiichi22** [comment]
Could you post a slam without this problem? D:
