### ISSUE TITLE
The process cannot access the file ......./slam_relay.cfg

### ISSUE THREAD

**Issue by Capple234** [SilentSys/SLAM#15]
[errorlog.txt](https://github.com/SilentSys/SLAM/files/83480/errorlog.txt)

This is causing my CSGO to crash.

**Comment by mads256c** [comment]
Because the program does not check if the file is in use. If it fails it should loop back and try again until it succeds.

**Comment by g0ddish** [comment]
I've fixed the issue properly in commit f30de7c see my pull request for an explanation. Thanks.
