### ISSUE TITLE
Garry's Mod

### ISSUE THREAD

**Issue by banksymate** [SilentSys/SLAM#33]
when using with garry's mod, status gets stuck on "working" (used exec slam, still doesn't work.)
doesn't play any music when i press the bind either

**Comment by g0ddish** [comment]
Can you elaborate more? I just recorded this because so many people say GMod is not working for them.

https://www.youtube.com/watch?v=Ly1wC5qFCfI&feature=youtu.be

**Comment by MCiLuZiioNz** [comment]
Can confirm I have SLAM working on Garry's Mod fine.

Remember the server you are on NEEDS TO have:
sv_use_steam_voice 0 and sv_allow_voice_from_file 1. By default SLAM will NOT work on most servers.
