### ISSUE TITLE
error

### ISSUE THREAD

**Issue by iceman201** [SilentSys/SLAM#38]
Upon starting SLAM after updating to v1.3.4 and pressing "Start" I get an error that reads:
"Access is denied. (Exception from HRESULT 0x80070005 (E_ACCESSDENIED)) See errorlog.txt for more info."
If I try to do exec slam in console, it simply says it couldn't execute it as if it's not running or the file isn't there although SLAM still gives me the tip and appears to be running. That's not really important, but I still thought it would be worth mentioning.
ERROR LOG
--------------------3/26/2016 7:13:44 PM-------------------- System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)) at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo) at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode) at System.Management.ManagementScope.InitializeGuts(Object o) at System.Management.ManagementScope.Initialize() at System.Management.ManagementObjectSearcher.Initialize() at System.Management.ManagementObjectSearcher.Get() at SLAM.Form1.GetFilepath(String ProcessName) at SLAM.Form1.PollRelayWorker_DoWork(Object sender, DoWorkEventArgs e)

**Comment by iceman201** [comment]
yeah when start run

**Comment by RayTheRaccoon** [comment]
I FOUND HOW TO FIX THIS
1st: Find ur songs that have ALOT of tags
2nd: Rename em to something small
3rd: do that to all your songs that have alot of tags and you should be okay

**Comment by iceman201** [comment]
sweet cheers man
