### ISSUE TITLE
Alias name is too long

### ISSUE THREAD

**Issue by BlakeJagged** [SilentSys/SLAM#39]
Upon the command "exec slam" it is now returning "Alias name is too long" this has happened on both garrys mod and cs:go. It worked the first time I used it but since then has not worked, always returning this error. I have verified my steam files, uninstalled and reinstalled, deleted all my tracks and re-added them, ran in admin mode... I've tried everything I can think of. Do you need any other information?

**Comment by 10se1ucgo** [comment]
Source engine has a limit as to how long an alias can be. This just means that one of the tags for your songs are too long, and the tag won't work. You can ignore it, or override any tag that is longer than ~~32~~ 31 characters.

**Comment by Andrew-Eathan** [comment]
same thing happened for me but the name of the music i'm playing was reduced to 3 characters
