### ISSUE TITLE
Host downloads on Github Releases

### ISSUE THREAD

**Issue by Ivoz** [SilentSys/SLAM#4]
It's possible to [tag a commit](http://git-scm.com/book/en/Git-Basics-Tagging) as a version number

And then use [this link](https://github.com/SilentSys/SLAM/releases/new) to make a release (or find it from the release tab on the project). You can drag and drop binaries / zips / msi's etc as downloadable files that will be part of the release.

The advantage is then you're hosting a file download from github which is a well known site, and it's easy to find the releases of the project on the [releases page](https://github.com/SilentSys/SLAM/releases).

If you don't care for this method, then feel free to close this issue and move on :) Thanks for the software!

**Comment by SilentSys** [comment]
Thanks for the tip. It is done.
