### ISSUE TITLE
linux?

### ISSUE THREAD

**Issue by Uramekus** [SilentSys/SLAM#41]
any type of linux support coming?
or it will continue to be bound on windows APIs on converting files?
 its sad to have to use pulseaudio features to redirect audio :ccc

**Comment by 10se1ucgo** [comment]
Don't mean to advertise, but I've created a similar (cross-platform) program, you can find it [here](https://github.com/10se1ucgo/pyjam).

**Comment by 10se1ucgo** [comment]
10/10

He removed a comment that had a link to my work, which has cross-platform support -- something that he doesn't care enough to implement. 

It's not a competition, I don't know why you're so aggressive.
