### ISSUE TITLE
[Suggestion] Use youtube-dl to accept youtube links

### ISSUE THREAD

**Issue by fullwall** [SilentSys/SLAM#44]
Would be really helpful to include https://rg3.github.io/youtube-dl/ and use it to automatically download and import mp3s from youtube.

**Comment by ElementTimes682** [comment]
I felt this would be good if I could use this to download a playlist that contains a OST.

**Comment by SilentSys** [comment]
This was addressed in 33faf30520d2cd4d2cbdf87b3ea9c9009a1e1cc4

Thanks!
