### ISSUE TITLE
Do i have to have a headset in cs:go?

### ISSUE THREAD

**Issue by Matty5763** [SilentSys/SLAM#47]
When i type exec slam then i do la to see what i can play then i type the number to play it then i got out of console and i press the assigned key i have to play whatever music i want to play and it doesn't play it. So do i need a headset to play the music?

**Comment by bronydell** [comment]
No, you don't need headset . Have you binded play button in settings of slam?
![image](https://cloud.githubusercontent.com/assets/7874195/18118878/3dc925ee-6f60-11e6-8ef8-53963168db6d.png)
