### ISSUE TITLE
Fade in and fade out

### ISSUE THREAD

**Issue by Osse** [SilentSys/SLAM#50]
I took the care of using Audacity to add fade in and fade out effects with to some of my WAVs before importing them in SLAM. When I keep the volume at the default 100% it seems like SLAM "maximizes" the volume dynamically so the fade in/out cannot be heard as I intended. If I set the volume at 60% it sounds pretty much like the original WAV. What is going on here? Is there an optimal volume setting in which the WAV is play as-is?

Thanks

**Comment by SilentSys** [comment]
This is definitely something the game is doing, not SLAM. See if you have any boost settings turned on in the games settings.
