### ISSUE TITLE
"too many commands" & "Ignoring command 'echo'"

### ISSUE THREAD

**Issue by thorN-Gaming** [SilentSys/SLAM#54]
I downloaded version 1.3.4 and loaded my songs, and when I went into a CS:GO deathmatch and typed 'exec slam' then 'la' it came up with 15-37 of my playlist even though I had all my songs loaded (1-37) in SLAM.exe. Also, when the songs loaded up in the console, it wasn't normal. It said "ignoring command 'echo'" and then the song number and song name. And at the very bottom after song 37, it said "too many commands" 
 Now, the 22 songs I **was** able to play still worked and I could select the song and play it, but I want my other songs that I loaded into SLAM aswell. Please help.
 ~ thorN

**Comment by SilentSys** [comment]
Valve made a mistake with an update. It was patched. Issue should be resolved.
