### ISSUE TITLE
CS:GO [F(1) KEYS DOESNT WORK]

### ISSUE THREAD

**Issue by pwnmactep** [SilentSys/SLAM#57]
SLAM works great, but (sorry)

If i play casual or any other gamemode the:
- F1,f2,f3 Keys etc. doesn´t work. 

Its a bit anoying if you heave to Vote... Kick,Vote Map,Timeout: 
- You can´t. (igonres Input)

Is there any Fix for this ?

Ty btw.

**Comment by SilentSys** [comment]
Did you ever use those keys as your play key or as a track key?

**Comment by pwnmactep** [comment]
Hi ,

No never

**Comment by SilentSys** [comment]
Is this only while SLAM is running? Or always?

Enter `unbind "F1"; unbind "F2"; bind "F3" "autobuy"` into console to reset those keys to their default binds.

Let me know if it's still happening. If it is, please provide a screenshot of all the tracks you have imported.

**Comment by pwnmactep** [comment]
Hi

I got autobuy on F1 allways and could vote normal.

With Running SLAM it worked now if i use your Console Command and Change it to F3

> unbind "F1"; unbind "F2"; bind "F3" "autobuy" 
> 


Thank you very much.
