### ISSUE TITLE
MAC!

### ISSUE THREAD

**Issue by The-AJ26** [SilentSys/SLAM#6]
I'm on a mac and I would love if you could make a version for mac :), if it won't work you can always tell the user to download soundflower and use that to automatically switch to soundflower when using the application and switch back when not using it.....thanks so much for I would love to use this app :)

**Comment by SilentSys** [comment]
Sorry, I don't have a mac, and have never developed for one.

**Comment by The-AJ26** [comment]
@SilentSys If you can't do it then maybe I can....... how is this working? Is it through client side or server side and how are you accessing it etc. If you can tell me the basics I can probably code a version for Mac. What I mostly need to know is if its client how are you accessing what files when. Thanks man.
