### ISSUE TITLE
Unlisted Song Error

### ISSUE THREAD

**Issue by PrestonIO** [SilentSys/SLAM#7]
If I type a number higher (not sure if lower) the program will quit due to the error. There must not be any catching system in place, otherwise it wasn't working. (Using v1.1.1)

**Comment by SilentSys** [comment]
Higher than what?

[This If statement](https://github.com/SilentSys/SLAM/blob/master/SLAM/Form1.vb#L264-L278) should be taking care of such bugs.

**Comment by PrestonIO** [comment]
It was higher than 9, but I wasn't expecting the program to just quit. Is there any way to just catch the exception instead of force closing the program? (I really never used VB so I don't know much about it)
