### ISSUE TITLE
[Bug] Can't convert short videos using YT import option

### ISSUE THREAD

**Issue by TypicalHog** [SilentSys/SLAM#74]
Longer videos are downloaded and converted just fine, but shorter ones (few seconds) fail to be converted.
They can be found in the "temp" folder with the .mp4 extension and are unplayable by the media player.

> --------------------21/03/2017 11:22:01 UTC--------------------
System.Runtime.InteropServices.COMException (0xC00D36C4): The byte stream type of the given URL is unsupported. (Exception from HRESULT: 0xC00D36C4)
   at NAudio.MediaFoundation.MediaFoundationInterop.MFCreateSourceReaderFromURL(String pwszURL, IMFAttributes pAttributes, IMFSourceReader& ppSourceReader)
   at NAudio.Wave.MediaFoundationReader.CreateReader(MediaFoundationReaderSettings settings)
   at NAudio.Wave.MediaFoundationReader..ctor(String file, MediaFoundationReaderSettings settings)
   at NAudio.Wave.MediaFoundationReader..ctor(String file)
   at SLAM.Form1.WaveCreator(String File, String outputFile, SourceGame Game)
   at SLAM.Form1.WavWorker_DoWork(Object sender, DoWorkEventArgs e)

**Comment by SilentSys** [comment]
I was able to import and use this [2 second long clip](https://www.youtube.com/watch?v=RPfCZhvj1Ng) just fine. Which video were you trying to import?

**Comment by TypicalHog** [comment]
Take a look:
[https://www.dropbox.com/s/1b0y7okaj6yo106/SLAM%20-%20error%20importing.mp4?dl=0](url)
If online playback quality is bad just download the video.

**Comment by pwnmactep** [comment]
Hi , 

every single link i download with the YT Option drops With the Error "Conversion Complete! However,the following files faild to convert:Von Paul Kalkbrenner - Aaron.mp4" for example..

**Comment by SilentSys** [comment]
Hm, I have a few ideas. @TypicalHog, could you please upload the mp4 in your temp folder exactly as is to Dropbox?

Thanks.

**Comment by TypicalHog** [comment]
There you go.
https://www.dropbox.com/s/ekj9gio9j7yzttu/Steam%20message%20alert.mp4?dl=0

**Comment by SilentSys** [comment]
Well, I'm able to import that mp4 just fine. Maybe your OS is missing something. Try downloading the Media Feature Pack for your version of windows from here: https://www.microsoft.com/en-ca/search/DownloadsDrillInResults.aspx?q=Media+Feature+Pack&cateorder=1_5_2_3&ftapplicableproducts=Windows

**Comment by TypicalHog** [comment]
It didn't help, I also tried running programs that fix registry issues but the problem is still there.

**Comment by pwnmactep** [comment]
Maybe include https://github.com/FFmpeg/FFmpeg ?

Would Maybe made it ...

**Comment by AreeseDT** [comment]
@SilentSys So I did some debugging on this issue, and it seems that it happens because the video that is being downloaded is corrupted or invalid.

**Comment by AreeseDT** [comment]
@SilentSys If you want to check out what I was playing around with, [this](https://github.com/AreeseDT/SLAM/tree/bug_74) version can successfully download and import the video in question.

**Comment by SilentSys** [comment]
@AreeseDT, That is very strange because both of the files you and @TypicalHog say are corrupt can be played on my system just fine, and I can import them into slam without an issue.

I see you included FFmpeg in your fork. A better solution may be to use FFmpeg to replace NAudio completely, since NAudio seems to be the source of these issues.

Can FFmpeg process those "corrupt" videos?

**Comment by AreeseDT** [comment]
@SilentSys I don't think its NAudio at all, because I can't even open the file to play it if I download it. In my fork the reason it can successfully download it is because it chooses a different download link.
![videofileerror](https://cloud.githubusercontent.com/assets/11260061/24327245/3ffc8f86-119a-11e7-9968-f01a88c7d55e.png)

**Comment by SilentSys** [comment]
I am able to play the audio file you provided. NAudio uses Microsoft Media Foundation to convert files, so if there is an issue with Microsoft Media Foundation, NAudio doesn't work. FFmpeg doesn't depend on Microsoft Media Foundation. That's my best guess so far. I think FFmpeg could still convert files downloaded by YoutubeExtractor.

**Comment by TypicalHog** [comment]
Something off topic. I realized downloaded files are .mp4 and not .mp3 (that makes download times much longer for people with a slow connection like myself), are .mp4's necessary?

**Comment by SilentSys** [comment]
YouTube, being a video sharing site, usually only has video streams. However, for more popular videos, YouTube generates some audio only and some video only streams which are meant to be streamed together (probably for efficiency and quality). At the moment, SLAM will detect if the video has an audio only stream, and download those instead.

**Comment by SilentSys** [comment]
This issue should be fixed in [v1.5.1](https://github.com/SilentSys/SLAM/tree/v1.5.1), please update SLAM and open a new issue if it persists.

**Comment by A-r-c-u-s** [comment]
Umm I keep getting this error I don't know what to do. Plz someone answer.
![capture](https://user-images.githubusercontent.com/44250745/47128206-e7559980-d255-11e8-9b67-05a011fe4dde.PNG)

**Comment by TypicalHog** [comment]
Just use 4k youtube to mp3 downloader instead.

**Comment by pwnmactep** [comment]
.netframework installed ?

**Comment by pwnmactep** [comment]
.Netframework installed?

Von meinem iPhone gesendet

**Comment by A-r-c-u-s** [comment]
No where can I download it?

**Comment by pwnmactep** [comment]
Just Google .Netframework take at least Version 3.5 . You can get it Right from Microsoft .

Von meinem iPhone gesendet
