### ISSUE TITLE
YoutTube

### ISSUE THREAD

**Issue by ra1N1336** [SilentSys/SLAM#75]
https://github.com/SilentSys/SLAM/blob/33faf30520d2cd4d2cbdf87b3ea9c9009a1e1cc4/SLAM/YTImport.Designer.vb#L99
![image](https://cloud.githubusercontent.com/assets/22330838/24147914/7e7b3564-0e4d-11e7-8293-5ba8ffee40e8.png)

**Comment by SilentSys** [comment]
Took me a while to figure out what you were getting at. I fixed the issue but it will probably be a little while until it is rolled out as a new release. Thanks!
