### ISSUE TITLE
Cant import from youtube.

### ISSUE THREAD

**Issue by tomisanhues2** [SilentSys/SLAM#76]
When I try importing a song, it downloads, then it says failed to convert FileName.MP4 

this is error regarding importing 
 
`--------------------21/03/2017 22:44:05 UTC--------------------
System.Runtime.InteropServices.COMException (0xC00D36C4): Excepción de HRESULT: 0xC00D36C4
   en NAudio.MediaFoundation.MediaFoundationInterop.MFCreateSourceReaderFromURL(String pwszURL, IMFAttributes pAttributes, IMFSourceReader& ppSourceReader)
   en NAudio.Wave.MediaFoundationReader.CreateReader(MediaFoundationReaderSettings settings)
   en NAudio.Wave.MediaFoundationReader..ctor(String file, MediaFoundationReaderSettings settings)
   en NAudio.Wave.MediaFoundationReader..ctor(String file)
   en SLAM.Form1.WaveCreator(String File, String outputFile, SourceGame Game)
   en SLAM.Form1.WavWorker_DoWork(Object sender, DoWorkEventArgs e)
`

**Comment by SilentSys** [comment]
Are you able to import files otherwise?

**Comment by TypicalHog** [comment]
He probably is. Only seems to happen with short videos, right?

**Comment by tomisanhues2** [comment]
Yes, I am able to import the normal way, I tried downloading around 3 minute songs

**Comment by SilentSys** [comment]
This issue should be fixed in [v1.5.1](https://github.com/SilentSys/SLAM/tree/v1.5.1), please update SLAM and open a new issue if it persists.
