### ISSUE TITLE
V1.5.1 Volume Issues

### ISSUE THREAD

**Issue by Djsoulhart** [SilentSys/SLAM#84]
So, with my main CPU I use V.1.5 and everything works.
My brother wanted to use the software as well, so we installed the latest version. V1.5.1

I went on to import two separate songs from youtube into SLAM.
I started the game up with both songs at 100%. 
They loaded and worked.

Now I know most people get mad because the sound is way to high, I  keep mine around 40-50.
I altered his to 45, loaded up the game. 
Started the songs and nothing happened, no sound.

I went back to change them to 100% and they worked again.

I do not know if you can change the volume anymore and that is an issue with the newest version,

**Comment by SilentSys** [comment]
Try v1.5.2, it should fix your issue. If not, you may need to choose a different volume. With different versions of SLAM and the different mic settings on different computers, 45 might be too low. Try 90 and go down from there.

**Comment by SilentSys** [comment]
Give v1.5.3 a shot. Should be fixed.
