### ISSUE TITLE
Still Not Working

### ISSUE THREAD

**Issue by LifeX0** [SilentSys/SLAM#85]
Hey i;m new to slam and downloaded the new 1.5.1 version of it. Everything is going fine except when I press my key that I binded to play my song "m" i cant hear anything. No music comes out when I use the key and I have tried everything. I switched to the NAudio and that didn't work and I used exec slam and all that stuff. It is because I only have 1 track or what? Please Help!

**Comment by TypicalHog** [comment]
Do you see the voice indicator at the bottom-left corner?

**Comment by LifeX0** [comment]
Yes but nothing comes out not even my voice

**Comment by LifeX0** [comment]
So I see the voice icon on the left hand corner but I hear static, or nothing at all

**Comment by Djsoulhart** [comment]
What you want to do is downgrade to V. 1.5
You will want to rebind the key to M.

Make sure you click start.
Open Console and type "exec slam"
load  your track (track list is "la") with what number it is.
Press your key.

Your voice will not go through, as the music took over your mic.

**Comment by LifeX0** [comment]
Okay I'm going to try that right now.

**Comment by LifeX0** [comment]
It worked! Thank you so much!

**Comment by SilentSys** [comment]
Yes, v1.5.1 had an issue. You can use v1.5.0 or the newer v1.5.2. They should both work. However, if you are keeping the tracks, be sure to delete any tracks that you imported using v1.5.1.
