### ISSUE TITLE
SLAM crashes csgo when starting a song

### ISSUE THREAD

**Issue by Pijmzhchus57** [SilentSys/SLAM#88]
From version 1.5.1 SLAM crashes my game whenever I start a song. I found out you have this new FFMPEG thing. When I go back to NAudio everything is ok but I want to see if the FFMPEG has better audio quality :DD Thank you for helping.

**Comment by TypicalHog** [comment]
FFMPEG should be the same quality if I'm correct.

**Comment by SilentSys** [comment]
@TypicalHog Yes, you are correct.

v1.5.1 has been deprecated. v1.5.3 should fix the issue, if not, open a new issue on GitHub.
