### ISSUE TITLE
Tracks not playable after updating from 1.5.0 to 1.5.3 (Logs included)

### ISSUE THREAD

**Issue by olokos** [SilentSys/SLAM#92]
I had quite big library on 1.5.0, I updated to 1.5.3 and with certain tracks uploaded before I updated, when I try to play them it just gives feedback from my mic and headphones instead of music.

Error logs says this

`--------------------27.07.2017 22:44:13 UTC--------------------
NReco.VideoConverter.FFMpegException: Invalid duration specification for t: 279,49283446712 (exit code: 1)
   w NReco.VideoConverter.FFMpegConverter.Invoke(String ffmpegArgs)
   w SLAM.Form1.FFMPEG_ConvertAndTrim(String inpath, String outpath, Int32 samplerate, Int32 channels, Double starttrim, Double length, Double volume)
   w SLAM.Form1.LoadTrack(SourceGame Game, Int32 index)
--------------------27.07.2017 22:44:14 UTC--------------------
NReco.VideoConverter.FFMpegException: Invalid duration specification for ss: 23,1249433106576 (exit code: 1)
   w NReco.VideoConverter.FFMpegConverter.Invoke(String ffmpegArgs)
   w SLAM.Form1.FFMPEG_ConvertAndTrim(String inpath, String outpath, Int32 samplerate, Int32 channels, Double starttrim, Double length, Double volume)
   w SLAM.Form1.LoadTrack(SourceGame Game, Int32 index)
--------------------27.07.2017 22:44:45 UTC--------------------
NReco.VideoConverter.FFMpegException: Invalid duration specification for ss: 2,24979591836735 (exit code: 1)
   w NReco.VideoConverter.FFMpegConverter.Invoke(String ffmpegArgs)
   w SLAM.Form1.FFMPEG_ConvertAndTrim(String inpath, String outpath, Int32 samplerate, Int32 channels, Double starttrim, Double length, Double volume)
   w SLAM.Form1.LoadTrack(SourceGame Game, Int32 index)
--------------------27.07.2017 22:49:06 UTC--------------------
NReco.VideoConverter.FFMpegException: Invalid duration specification for ss: 23,1249433106576 (exit code: 1)
   w NReco.VideoConverter.FFMpegConverter.Invoke(String ffmpegArgs)
   w SLAM.Form1.FFMPEG_ConvertAndTrim(String inpath, String outpath, Int32 samplerate, Int32 channels, Double starttrim, Double length, Double volume)
   w SLAM.Form1.LoadTrack(SourceGame Game, Int32 index)
--------------------27.07.2017 22:49:31 UTC--------------------
NReco.VideoConverter.FFMpegException: Invalid duration specification for ss: 52,3419501133787 (exit code: 1)
   w NReco.VideoConverter.FFMpegConverter.Invoke(String ffmpegArgs)
   w SLAM.Form1.FFMPEG_ConvertAndTrim(String inpath, String outpath, Int32 samplerate, Int32 channels, Double starttrim, Double length, Double volume)
   w SLAM.Form1.LoadTrack(SourceGame Game, Int32 index)
--------------------27.07.2017 22:49:35 UTC--------------------
NReco.VideoConverter.FFMpegException: Invalid duration specification for ss: 152,722448979592 (exit code: 1)
   w NReco.VideoConverter.FFMpegConverter.Invoke(String ffmpegArgs)
   w SLAM.Form1.FFMPEG_ConvertAndTrim(String inpath, String outpath, Int32 samplerate, Int32 channels, Double starttrim, Double length, Double volume)
   w SLAM.Form1.LoadTrack(SourceGame Game, Int32 index)
`

**Comment by SilentSys** [comment]
Fixed by 52c6c07d9142f66283cf65e30608a3523be63757. Please update to v1.5.4.

Thanks!

**Comment by olokos** [comment]
you're welcome, good job man 👍
