### ISSUE TITLE
[BUG] Slam not able to play trimmed songs

### ISSUE THREAD

**Issue by DenislavMihaylov** [SilentSys/SLAM#93]
Hi, first, great work. Could you please verify if this is an indeed bug or it's just me. After I trim a song via SLAM interface and load it, the song can not be played, all I hear is an echo and the sound from my mic. 
I have no issues with untrimmed songs.

Thanks and keep up the good work.

**Comment by SilentSys** [comment]
Fixed by 52c6c07d9142f66283cf65e30608a3523be63757. Please update to v1.5.4.

Thanks!
